apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
spec:
  selector:
    app: nextjs
  type: NodePort   # Good for Minikube
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  # Optional: can be omitted to auto-assign

